/* dconf-editor.c generated by valac 0.32.0.37-81db9, the Vala compiler
 * generated from dconf-editor.vala, do not modify */

/*
  This file is part of Dconf Editor

  Dconf Editor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Dconf Editor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Dconf Editor.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include "config.h"
#include <stdio.h>
#include <gdk/gdk.h>


#define TYPE_CONFIGURATION_EDITOR (configuration_editor_get_type ())
#define CONFIGURATION_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIGURATION_EDITOR, ConfigurationEditor))
#define CONFIGURATION_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIGURATION_EDITOR, ConfigurationEditorClass))
#define IS_CONFIGURATION_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIGURATION_EDITOR))
#define IS_CONFIGURATION_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIGURATION_EDITOR))
#define CONFIGURATION_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIGURATION_EDITOR, ConfigurationEditorClass))

typedef struct _ConfigurationEditor ConfigurationEditor;
typedef struct _ConfigurationEditorClass ConfigurationEditorClass;
typedef struct _ConfigurationEditorPrivate ConfigurationEditorPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_DCONF_WINDOW (dconf_window_get_type ())
#define DCONF_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DCONF_WINDOW, DConfWindow))
#define DCONF_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DCONF_WINDOW, DConfWindowClass))
#define IS_DCONF_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DCONF_WINDOW))
#define IS_DCONF_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DCONF_WINDOW))
#define DCONF_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DCONF_WINDOW, DConfWindowClass))

typedef struct _DConfWindow DConfWindow;
typedef struct _DConfWindowClass DConfWindowClass;

struct _ConfigurationEditor {
	GtkApplication parent_instance;
	ConfigurationEditorPrivate * priv;
};

struct _ConfigurationEditorClass {
	GtkApplicationClass parent_class;
};

struct _ConfigurationEditorPrivate {
	GNotification* notification;
	gboolean notification_active;
	guint notification_number;
};


static gpointer configuration_editor_parent_class = NULL;

GType configuration_editor_get_type (void) G_GNUC_CONST;
#define CONFIGURATION_EDITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CONFIGURATION_EDITOR, ConfigurationEditorPrivate))
enum  {
	CONFIGURATION_EDITOR_DUMMY_PROPERTY
};
static void configuration_editor_copy_cb (ConfigurationEditor* self, GSimpleAction* action, GVariant* gvariant);
static void _configuration_editor_copy_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
void configuration_editor_about_cb (ConfigurationEditor* self);
static void _configuration_editor_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
static void configuration_editor_quit_cb (ConfigurationEditor* self);
static void _configuration_editor_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
gint configuration_editor_main (gchar** args, int args_length1);
ConfigurationEditor* configuration_editor_new (void);
ConfigurationEditor* configuration_editor_construct (GType object_type);
static gint configuration_editor_real_handle_local_options (GApplication* base, GVariantDict* options);
static void configuration_editor_real_startup (GApplication* base);
DConfWindow* dconf_window_new (void);
DConfWindow* dconf_window_construct (GType object_type);
GType dconf_window_get_type (void) G_GNUC_CONST;
static void configuration_editor_real_activate (GApplication* base);
void configuration_editor_copy (ConfigurationEditor* self, const gchar* text);
static gboolean __lambda4_ (ConfigurationEditor* self);
static gboolean ___lambda4__gsource_func (gpointer self);
static void configuration_editor_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GOptionEntry CONFIGURATION_EDITOR_option_entries[2] = {{"version", 'v', 0, G_OPTION_ARG_NONE, NULL, "Print release version and exit", NULL}, {NULL}};
static const GActionEntry CONFIGURATION_EDITOR_action_entries[3] = {{"copy", _configuration_editor_copy_cb_gsimple_action_activate_callback, "s"}, {"about", _configuration_editor_about_cb_gsimple_action_activate_callback}, {"quit", _configuration_editor_quit_cb_gsimple_action_activate_callback}};

static void _configuration_editor_copy_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
#line 26 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	configuration_editor_copy_cb ((ConfigurationEditor*) self, action, parameter);
#line 108 "dconf-editor.c"
}


static void _configuration_editor_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
#line 26 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	configuration_editor_about_cb ((ConfigurationEditor*) self);
#line 115 "dconf-editor.c"
}


static void _configuration_editor_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
#line 26 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	configuration_editor_quit_cb ((ConfigurationEditor*) self);
#line 122 "dconf-editor.c"
}


gint configuration_editor_main (gchar** args, int args_length1) {
	gint result = 0;
	ConfigurationEditor* app = NULL;
	ConfigurationEditor* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 42 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	setlocale (LC_ALL, "");
#line 43 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 44 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 45 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	textdomain (GETTEXT_PACKAGE);
#line 47 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = configuration_editor_new ();
#line 47 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	app = _tmp0_;
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = args;
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1__length1 = args_length1;
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	result = _tmp2_;
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (app);
#line 48 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return result;
#line 157 "dconf-editor.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 40 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return configuration_editor_main (argv, argc);
#line 167 "dconf-editor.c"
}


ConfigurationEditor* configuration_editor_construct (GType object_type) {
	ConfigurationEditor * self = NULL;
#line 53 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self = (ConfigurationEditor*) g_object_new (object_type, "application-id", "ca.desrt.dconf-editor", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 55 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_application_add_main_option_entries ((GApplication*) self, CONFIGURATION_EDITOR_option_entries);
#line 51 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return self;
#line 179 "dconf-editor.c"
}


ConfigurationEditor* configuration_editor_new (void) {
#line 51 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return configuration_editor_construct (TYPE_CONFIGURATION_EDITOR);
#line 186 "dconf-editor.c"
}


static gint configuration_editor_real_handle_local_options (GApplication* base, GVariantDict* options) {
	ConfigurationEditor * self;
	gint result = 0;
	GVariantDict* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 58 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self = (ConfigurationEditor*) base;
#line 58 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_val_if_fail (options != NULL, 0);
#line 60 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = options;
#line 60 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = g_variant_dict_contains (_tmp0_, "version");
#line 60 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	if (_tmp1_) {
#line 205 "dconf-editor.c"
		FILE* _tmp2_ = NULL;
#line 63 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		_tmp2_ = stdout;
#line 63 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		fprintf (_tmp2_, "%1$s %2$s\n", "dconf-editor", VERSION);
#line 64 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		result = EXIT_SUCCESS;
#line 64 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		return result;
#line 215 "dconf-editor.c"
	}
#line 66 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	result = -1;
#line 66 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return result;
#line 221 "dconf-editor.c"
}


static void configuration_editor_real_startup (GApplication* base) {
	ConfigurationEditor * self;
	const gchar* _tmp0_ = NULL;
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp1_ = NULL;
	GdkScreen* _tmp2_ = NULL;
	DConfWindow* _tmp3_ = NULL;
	DConfWindow* _tmp4_ = NULL;
#line 69 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self = (ConfigurationEditor*) base;
#line 71 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	G_APPLICATION_CLASS (configuration_editor_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 73 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = _ ("dconf Editor");
#line 73 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_set_application_name (_tmp0_);
#line 74 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_window_set_default_icon_name ("dconf-editor");
#line 76 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_action_map_add_action_entries ((GActionMap*) self, CONFIGURATION_EDITOR_action_entries, G_N_ELEMENTS (CONFIGURATION_EDITOR_action_entries), self);
#line 78 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = gtk_css_provider_new ();
#line 78 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	css_provider = _tmp1_;
#line 79 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_css_provider_load_from_resource (css_provider, "/ca/desrt/dconf-editor/ui/dconf-editor.css");
#line 80 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_ = gdk_screen_get_default ();
#line 80 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_style_context_add_provider_for_screen (_tmp2_, (GtkStyleProvider*) css_provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 82 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp3_ = dconf_window_new ();
#line 82 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_object_ref_sink (_tmp3_);
#line 82 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp4_ = _tmp3_;
#line 82 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp4_);
#line 82 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (_tmp4_);
#line 69 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (css_provider);
#line 267 "dconf-editor.c"
}


static void configuration_editor_real_activate (GApplication* base) {
	ConfigurationEditor * self;
	GtkWindow* _tmp0_ = NULL;
#line 85 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self = (ConfigurationEditor*) base;
#line 87 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 87 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_window_present (_tmp0_);
#line 280 "dconf-editor.c"
}


static void configuration_editor_copy_cb (ConfigurationEditor* self, GSimpleAction* action, GVariant* gvariant) {
	GVariant* _tmp0_ = NULL;
	GVariant* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 98 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (self != NULL);
#line 98 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (action != NULL);
#line 100 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = gvariant;
#line 100 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	if (_tmp0_ == NULL) {
#line 101 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		return;
#line 298 "dconf-editor.c"
	}
#line 102 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = gvariant;
#line 102 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_ = g_variant_get_string ((GVariant*) _tmp1_, NULL);
#line 102 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	configuration_editor_copy (self, _tmp2_);
#line 306 "dconf-editor.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 108 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return self ? g_object_ref (self) : NULL;
#line 313 "dconf-editor.c"
}


static gboolean __lambda4_ (ConfigurationEditor* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
#line 123 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = self->priv->notification_active;
#line 123 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	if (_tmp0_ == FALSE) {
#line 124 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		result = G_SOURCE_CONTINUE;
#line 124 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		return result;
#line 328 "dconf-editor.c"
	}
#line 125 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_application_withdraw_notification ((GApplication*) self, "copy");
#line 126 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv->notification_active = FALSE;
#line 127 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	result = G_SOURCE_REMOVE;
#line 127 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return result;
#line 338 "dconf-editor.c"
}


static gboolean ___lambda4__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda4_ ((ConfigurationEditor*) self);
#line 122 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	return result;
#line 347 "dconf-editor.c"
}


void configuration_editor_copy (ConfigurationEditor* self, const gchar* text) {
	GdkDisplay* display = NULL;
	GdkDisplay* _tmp0_ = NULL;
	GdkDisplay* _tmp1_ = NULL;
	GdkDisplay* _tmp2_ = NULL;
	GtkClipboard* clipboard = NULL;
	GdkDisplay* _tmp3_ = NULL;
	GtkClipboard* _tmp4_ = NULL;
	GtkClipboard* _tmp5_ = NULL;
	GtkClipboard* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	gboolean _tmp11_ = FALSE;
	guint _tmp13_ = 0U;
	GNotification* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	GNotification* _tmp16_ = NULL;
#line 105 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (self != NULL);
#line 105 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (text != NULL);
#line 108 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = gdk_display_get_default ();
#line 108 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 108 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	display = _tmp1_;
#line 109 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_ = display;
#line 109 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	if (_tmp2_ == NULL) {
#line 110 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		_g_object_unref0 (display);
#line 110 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		return;
#line 388 "dconf-editor.c"
	}
#line 112 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp3_ = display;
#line 112 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp4_ = gtk_clipboard_get_default (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, gdk_display_get_type (), GdkDisplay));
#line 112 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 112 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	clipboard = _tmp5_;
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp6_ = clipboard;
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp7_ = text;
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp8_ = text;
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp9_ = strlen (_tmp8_);
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp10_ = _tmp9_;
#line 113 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_clipboard_set_text (_tmp6_, _tmp7_, _tmp10_);
#line 116 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp11_ = self->priv->notification_active;
#line 116 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	if (_tmp11_ == TRUE) {
#line 414 "dconf-editor.c"
		guint _tmp12_ = 0U;
#line 118 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		_tmp12_ = self->priv->notification_number;
#line 118 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		g_source_remove (_tmp12_);
#line 119 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
		self->priv->notification_active = FALSE;
#line 422 "dconf-editor.c"
	}
#line 122 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp13_ = g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 30, ___lambda4__gsource_func, g_object_ref (self), g_object_unref);
#line 122 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv->notification_number = _tmp13_;
#line 129 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv->notification_active = TRUE;
#line 131 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp14_ = self->priv->notification;
#line 131 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp15_ = text;
#line 131 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_notification_set_body (_tmp14_, _tmp15_);
#line 132 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_application_withdraw_notification ((GApplication*) self, "copy");
#line 133 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp16_ = self->priv->notification;
#line 133 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_application_send_notification ((GApplication*) self, "copy", _tmp16_);
#line 105 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (clipboard);
#line 105 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (display);
#line 446 "dconf-editor.c"
}


void configuration_editor_about_cb (ConfigurationEditor* self) {
	gchar** authors = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint authors_length1 = 0;
	gint _authors_size_ = 0;
	GtkWindow* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 140 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (self != NULL);
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = g_strdup ("Robert Ancell");
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = g_strdup ("Arnaud Bonatti");
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_ = g_new0 (gchar*, 2 + 1);
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_[0] = _tmp0_;
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp2_[1] = _tmp1_;
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	authors = _tmp2_;
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	authors_length1 = 2;
#line 142 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_authors_size_ = authors_length1;
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp3_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp4_ = _ ("dconf Editor");
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp5_ = _ ("Directly edit your entire configuration database");
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp6_ = _ ("Copyright \xc2\xa9 2010-2014 – Canonical Ltd\n" \
"Copyright \xc2\xa9 2015-2016 – Arnaud Bonatti");
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp7_ = _ ("translator-credits");
#line 143 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_show_about_dialog (_tmp3_, "program-name", _tmp4_, "version", VERSION, "comments", _tmp5_, "copyright", _tmp6_, "license-type", GTK_LICENSE_GPL_3_0, "wrap-license", TRUE, "authors", authors, "translator-credits", _tmp7_, "logo-icon-name", "dconf-editor", NULL, NULL);
#line 140 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	authors = (_vala_array_free (authors, authors_length1, (GDestroyNotify) g_free), NULL);
#line 494 "dconf-editor.c"
}


static void configuration_editor_quit_cb (ConfigurationEditor* self) {
	GtkWindow* _tmp0_ = NULL;
#line 156 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_return_if_fail (self != NULL);
#line 158 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 158 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
#line 160 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_application_quit ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 508 "dconf-editor.c"
}


static void configuration_editor_class_init (ConfigurationEditorClass * klass) {
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	configuration_editor_parent_class = g_type_class_peek_parent (klass);
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	g_type_class_add_private (klass, sizeof (ConfigurationEditorPrivate));
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	((GApplicationClass *) klass)->handle_local_options = configuration_editor_real_handle_local_options;
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	((GApplicationClass *) klass)->startup = configuration_editor_real_startup;
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	((GApplicationClass *) klass)->activate = configuration_editor_real_activate;
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	G_OBJECT_CLASS (klass)->finalize = configuration_editor_finalize;
#line 525 "dconf-editor.c"
}


static void configuration_editor_instance_init (ConfigurationEditor * self) {
	const gchar* _tmp0_ = NULL;
	GNotification* _tmp1_ = NULL;
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv = CONFIGURATION_EDITOR_GET_PRIVATE (self);
#line 94 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp0_ = _ ("Copied to clipboard");
#line 94 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_tmp1_ = g_notification_new (_tmp0_);
#line 94 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv->notification = _tmp1_;
#line 95 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self->priv->notification_active = FALSE;
#line 542 "dconf-editor.c"
}


static void configuration_editor_finalize (GObject* obj) {
	ConfigurationEditor * self;
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CONFIGURATION_EDITOR, ConfigurationEditor);
#line 94 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	_g_object_unref0 (self->priv->notification);
#line 18 "/run/media/triton/Guerre/jhbuild/jhbuild/dconf-editor/editor/dconf-editor.vala"
	G_OBJECT_CLASS (configuration_editor_parent_class)->finalize (obj);
#line 554 "dconf-editor.c"
}


GType configuration_editor_get_type (void) {
	static volatile gsize configuration_editor_type_id__volatile = 0;
	if (g_once_init_enter (&configuration_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ConfigurationEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) configuration_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ConfigurationEditor), 0, (GInstanceInitFunc) configuration_editor_instance_init, NULL };
		GType configuration_editor_type_id;
		configuration_editor_type_id = g_type_register_static (gtk_application_get_type (), "ConfigurationEditor", &g_define_type_info, 0);
		g_once_init_leave (&configuration_editor_type_id__volatile, configuration_editor_type_id);
	}
	return configuration_editor_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



